### ISSUE TITLE
Test failing for Navbar

### ISSUE THREAD

**Issue by dextel2** [couds/react-bulma-components#106]
I'm running `npm test` and it is failing the tests, the way I'm implementing is

`import { Navbar } from "react-bulma-components/full";`

but if I use the recommended way i.e. 

`import Navbar from "react-bulma-components/lib/components/navbar";`
It is breaking the entire Navbar

when I run `npm test` it is throwing this error

```
src\App.test.js
  ● Test suite failed to run
    ReferenceError: window is not defined

      at Object.<anonymous> (node_modules/react-bulma-components/full/index.js:1:346)
      at Object.<anonymous> (src/Components/Layout/Header.jsx:2:13)      at Object.<anonymous> (src/App.js:3:15)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.249s
Ran all test suites.
```

I'm using `react-bulma-components@2.0.0`

**Comment by couds** [comment]
Hi @dextel2 

Can you try one on this?

1. can you add
```
"globals": {
    "window": true
  }
```
to your jest config?

2. try using `import { Navbar } from "react-bulma-components` and include the css file on your html or your webpack bundle.

Let me know if this help

**Comment by dextel2** [comment]
Hi @couds, It might sound silly of me, but I do not have a `jest.config` I'm simply running `App.test.js` and for 2. `import Navbar from "react-bulma-components/lib/components/navbar";` , shouldn't this work?

**Comment by dextel2** [comment]
Hi @couds , I need not create `jest.config` as it's simply running `App.test.js`, as to the second solution it worked perfectly thank you now I'm getting other Component's error. Thank you :)

**Comment by dextel2** [comment]
Can you please explain how jest config would've helped?

**Comment by couds** [comment]
Hi @dextel2 

When running the tests jest assume that the environment is node but in this case need to be the browser this is because the `full` export include the styles and will try to create the style tags on the window. 

I not tested it my self but seem that adding that setting tell jest that the global window it's available (I don't know fire sure but maybe use jsdom or we need to setup de jsdom ourself).

The reason the other import works it's because do not include the styles they are exported on the case file. So the bundle do not need window to be available.

I hope this help.
