### ISSUE TITLE
Pagination renders as div but is expected to render as nav?

### ISSUE THREAD

**Issue by dfee** [couds/react-bulma-components#110]
There is a defaultProp for it: https://github.com/couds/react-bulma-components/blob/3b13b738b0bfd0bc82104b6913d3ba1367a6196a/src/components/pagination/pagination.js#L42

But there's not a propType, nor is that prop consumed. Therefore, should `Element` render a `div` or a `nav`?

**Comment by dfee** [comment]
The same issue occurs in: [`CardHead`](https://github.com/couds/react-bulma-components/blob/master/src/components/modal/components/card/head.js), [`CardFoot`](https://github.com/couds/react-bulma-components/blob/master/src/components/modal/components/card/foot.js), [`ModalCardTitle`](https://github.com/couds/react-bulma-components/blob/master/src/components/modal/components/card/title.js#L13), and a few other places.

Interestingly, in some components, like [`DropdownItem`](https://github.com/couds/react-bulma-components/blob/master/src/components/dropdown/components/item.js) there is **no** `renderAs` prop (so it'll be rendered as a `div`) despite that `Element` is receiving a `title`.

I'd suggest maybe that's a bug and it should have a default prop of `a` so that `title` is meaningful and it's aligned with: https://bulma.io/documentation/components/dropdown/

**Comment by MrCreeper1008** [comment]
When a defaultProp, in this case `renderAs`, it will be automatically available in `this.props`, thus `this.props.renderAs` is defined and is consumed by `<Element />`.  
React doc: https://reactjs.org/docs/typechecking-with-proptypes.html#default-prop-values

**Comment by dfee** [comment]
That is how it works, but my comment was on the general inconsistency throughout this package. Some components have:
1) `renderAs` statically defined on the `Element` component constructor, 
2) `renderAs` as a `defaultProp` but not as a `propType`,
3) `renderAs` as a `defaultProp` and also as a `propType`
4) no `renderAs` specified (defaulting to `div`).

That said, what about DropdownItem not being default as `a` yet having a `title` prop? I think it should by default be an `a`.

**Comment by couds** [comment]
Hi @dfee 

1. The renderAs props sometimes does not make sense to be dynamic on some components (mostly because is how that bulma component works). that is way some element have it statically.

2. The example you put before about the component having defaultProp and not propTypes it not right because it have the proptypes `modifiers.propTypes` https://github.com/couds/react-bulma-components/blob/3b13b738b0bfd0bc82104b6913d3ba1367a6196a/src/modifiers/index.js#L10

3. There are cases that the component do not has the `modifiers.propTypes` these cases the component have the renderAs PropType (also there is posible to be a error when I changed the renderAs to be in almost all components that make sense)

4. When the component use Element and alse the default render is a div it have the renderAs PropType and defaultProp sing the modifier object https://github.com/couds/react-bulma-components/blob/master/src/modifiers/index.js 

About your last comment I don't understand why you said that because the DropdownItem have `title` should be an `a`  From the HTML spec

```
The title attribute represents advisory information for the element, such as would be appropriate for a tooltip. On a link, this could be the title or a description of the target resource; on an image, it could be the image credit or a description of the image; on a paragraph, it could be a footnote or commentary on the text; on a citation, it could be further information about the source; on interactive content, it could be a label for, or instructions for, use of the element; and so forth. The value is text.
```
https://www.w3.org/TR/html51/dom.html#the-title-attribute

NOTE: Yes its possible that some component are outdated and do not have the correct version of the renderAs Prop as you pinpoint on #111 

What I don't understand its your point on this issue in the title you said "Pagination renders as div but is expected to render as nav?" but the component is rendered as a `nav` (the expected html element) as you can see on https://github.com/couds/react-bulma-components/blob/3b13b738b0bfd0bc82104b6913d3ba1367a6196a/src/components/pagination/__test__/__snapshots__/pagination.test.js.snap#L4

Can you please specify the goal of this issue or close it is not a issue any more?

Thanks!

**Comment by dfee** [comment]
Yeah, I put together typescript types for this package last night and was looking for clarity. I need to figure out how to merge in that declaration file to this package. I can close now.

**Comment by couds** [comment]
@dfee Kudos for the TS types (I'm not really a fan of TS so I didn't learn but will be great if you share the type definitions.. if you need any clarification please ask.
