### ISSUE TITLE
ModalCardBody should accept function for `renderAs`

### ISSUE THREAD

**Issue by dfee** [couds/react-bulma-components#111]
https://github.com/couds/react-bulma-components/blob/master/src/components/modal/components/card/body.js#L26

It's the anomaly component for not accepting `function`.

**Comment by couds** [comment]
Hi @dfee thanks for your report, this component should not have the renderAs PropType defined and use the one inherit from the modifier. I will do this change later today.

**Comment by couds** [comment]
I just saw that the modifier do not have the renderAs (that was my mistake because I added on a branch I never published/merged).. because I'm on that part now I will also fix that

**Comment by dfee** [comment]
I didn't see a PropType defined in any of the modifiers. Did you mean that it should just have the `defaultPropType`?

**Comment by couds** [comment]
That was my mistake (I added the proptype to the modifier (the https://github.com/couds/react-bulma-components/blob/master/src/modifiers/index.js) but somehow I didn't merge that branch and got lost between changes). as you said all renderAs Props yous accept String and Function as a valid value. I'm working on that. 

But because nothing can be simple there are a few exceptions to that rule (The Breadcrumb components for example...) I'm thinking it make sense to change that component to be more dummy and instead of the array of `items` use a children component (Like `Colums`/`Columns.Column`) to render them. and do the same approach n other components that behave in that way to simplify and standardize the propTypes.
