### ISSUE TITLE
Can't use variables.sass

### ISSUE THREAD

**Issue by xetrics** [couds/react-bulma-components#190]
I am currently trying to use node-sass-chokidar as described in the docs to use CRA without ejecting my project. When I try to complile, I get this error from within the react-bulma-components package:

```
Failed to compile.

./node_modules/react-bulma-components/lib/components/button/button.sass (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-3!./node_modules/react-bulma-components/lib/components/button/button.sass)
undefined
^
      File to import not found or unreadable: ~_variables.sass.
      in C:\Users\nathan\Desktop\rust_battles\node_modules\react-bulma-components\lib\components\utils.sass (line 3, column 1)




```

I am using the build script straight from the docs. My project hierarchy: 
```
/src
    /scss
        ./_variables.sass
         ./style.sass          
    /components
        /layouts
            ./Home.jsx
        ./Navbar.jsx
        ./App.js
        ./index.js
        ./style.css (output)
```

Here is where I am importing button.sass ((the file currently throwing the error)
```js
import React, { Component } from "react"
import { Navbar as Nav} from "react-bulma-components/lib/components/navbar"
import { Button } from "react-bulma-components/lib/components/button"


class Navbar extends Component {
    render() {
        return(
            <Nav color="primary">
                <Nav.Brand>
                    <Nav.Item renderAs="a" href="#"><img src="https://via.placeholder.com/350x150" alt="" /></Nav.Item>
                </Nav.Brand>
                <Nav.Menu>
                <Nav.Container position="end">
                    <Nav.Item><Button color="primary">Login</Button></Nav.Item>
                </Nav.Container>
                </Nav.Menu>
            </Nav>
        )
    }
}

export default Navbar
```
I am doing everything textbook from the docs and still having issues.

_variables.sass: https://hastebin.com/mafenuwoho.sass

Ideally I want to use the `[RECOMENDED]` import method of importing straight from lib/components/xxxx, as well as override bulma variables in _variables.sass

**Comment by couds** [comment]
Hi, which version of the library are you using?

**Comment by efeichen** [comment]
Check the [advanced setup](https://github.com/couds/react-bulma-components#advanced) portion of this Github repo's README. It provides more details than that on NPM.

If this solves your problem then maybe updating the NPM docs will be the next best move since it's the first result that comes up on Google.

**Comment by loopmode** [comment]
I'm trying out @next version for typescript support, in an electron-webpack application. I don't even want advanced setup as I don't need variable overrides and I don't care about bundle size. 
Still I must provide _variables.sass when I import individual components, otherwise compilation fails. It's very inconvenient. 
I now customized my webpack setup to include a special folder `src/renderer/bulma` that contains a single empty _variable.scss.
Not terrible, but far from good 😄
