### ISSUE TITLE
Configuration and setup of _variables.sass

### ISSUE THREAD

**Issue by RyanChristian4427** [couds/react-bulma-components#212]
Have you by any chance thought about setting your variable system to be something more like  [Buefy's](https://buefy.org/documentation/customization)?

CRA currently does not allow setting the `baseUrl` to anything but `src` and `node_modules`, which is unfortunate, but CRA has never been ones to really care too much about other use cases. So because I'd need to put `_variables.sass` directly under `src`, I need to skip out on this library. That's just a bit too messy for my liking, as ideally for myself, an `index` file should be the only bare file under `src`.

Buefy's system is much simpler, and, in my opinion, makes much more sense. I can create a `_main.scss` file, anywhere in my app, that will import the library, as well as any alterations I have done on top of it. I could set all the variables in that one file, or just import a dozen files; it really does not matter.

Just my thoughts on the matter, and a way this could possible become better.

**Comment by couds** [comment]
Thanks for your suggestion but I probably will not change the approach. I like to only import the necessary styles and not all the styles without doing it manually (that’s will be the result using the approach you suggest)

The variables in the src folder is an example you can put it anywhere you like just need to point the correct variable to the folder (NODE_PATH) 

I have to test if the baseUrl of CRA can handle multiple path’s like the env variable but you do not need necessarily to put it in the src.

PD. I don’t think having the variables on the src folder as a messy. Because that is a file that affect the whole project (like the .env for example).

Sorry this approach didn’t like you but I will keep it
