### ISSUE TITLE
Use prettier for project?

### ISSUE THREAD

**Issue by MrCreeper1008** [couds/react-bulma-components#214]
Right now `prettier` isn't used by the project. Would be great if it is.

**Comment by couds** [comment]
Hi can you tell me the benefits of adding this on the top of the eslint?

**Comment by MrCreeper1008** [comment]
It is an automatic, opinionated code formatter so you dont have to manually format the code yourself. It also enforces consistent code style which i think is important. also its supre convenient to not having to worry about formatting since it does all the work..

**Comment by couds** [comment]
But what is does in this PR that eslint . —fix’ does not?

**Comment by MrCreeper1008** [comment]
https://github.com/prettier/prettier-eslint/issues/101  
I think this should answer your question :)

**Comment by RobJacobson** [comment]
Seconded. Prettier enforces visual styles like indentation and object formatting, rather than substantive styles like eslint.  It's more and more common across the web.  If you use Prettier, then your code will look more similar with other people's code.

Prettier is highly opinionated and it enforces those opinions. One of the best statements I've read is that "I hate how Prettier reformats my own code, but I love how it fixes/cleans up my coworkers' code." It makes all of the code look consistent, regardless of who wrote it.
