### ISSUE TITLE
Updated to newest React and get this error

### ISSUE THREAD

**Issue by Michael-Reich** [couds/react-bulma-components#25]
I went from 15 to v16 the latest version and I get this error:

```
warning.js:33 Warning: Unsafe legacy lifecycles will not be called for components using new component APIs.

Navbar uses getDerivedStateFromProps() but also contains the following legacy lifecycles:
  componentWillReceiveProps

The above lifecycles should be removed. Learn more about this warning here:
```

**Comment by couds** [comment]
Hi @Michael-Reich 

For now this is intended. the Navbar component its using the new static lifecycle method `getDerivedStateFromProps` but I kept the `componentWillReceiveProps` on this release because will be a breaking change. on the next major release I will remove the `componentWillReceiveProps` method and change the dependency of react to > 16.3

**Comment by Michael-Reich** [comment]
Ah ok so I can ignore it for now?

Also, the Burger Menu isn't working as expected, I used the common setup from the doc. But if I click on it nothing happens.

**Comment by couds** [comment]
Clossing this due inactivity
