### ISSUE TITLE
[HELP] NextJs instructions suggests outdated package

### ISSUE THREAD

**Issue by wozza35** [couds/react-bulma-components#292]
I've followed the installation guide for NextJS version >= 9

When starting the NextJS server, I get the following message:

`Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected. See here for more info: https://err.sh/next.js/built-in-css-disabled`

It seems that since NextJS v9, SASS support was built-in and they now consider `@zeit/next-sass` to be outdated. As a result I don't seem to be able to use CSS modules to style components. 

Is there a newer way to setup Bulma with NextJS?

**Comment by couds** [comment]
We are working on V4, and we will remove the advance configuration, in this you can follow the normal configuration of your framework to setup the bulma saas, 

you could probably do the same on V3 using the [Basic configuration](https://github.com/couds/react-bulma-components#basic) 

Bu instead of importing

```javascript
import 'react-bulma-components/dist/react-bulma-components.min.css';
```

you follow the tutorial of importing normal saas (and import bulma)
