### ISSUE TITLE
[HELP] Request to build transpiled version of lib

### ISSUE THREAD

**Issue by STUkh** [couds/react-bulma-components#306]
Since Jest doesn't natively support ES6 modules it would be great to have pre-build version of `react-bulma-components` and NOT to transpile whole library on each test run.

The only solution for Jest now is to exclude `react-bulma-components` from node_modules 
``` 
transformIgnorePatterns: ['/node_modules/(?!react-bulma-components)(.*)'],
```

But this adds extra-time for each test-run.

**Comment by couds** [comment]
Hi @STUkh you can import the transpiled version from `react-bulma-components/lib` (for the advance setup) and from the default `react-bulma-component`.

Both are already transpiled, the difference its that the base does not include the css (you need to import the bulma styles your self)

I recommend if possible to do the basic, since in V4 we will not include the bulma styles (to difficult to maintain on all the different frameworks)
