### ISSUE TITLE
[NEXTJS] Refusing to import components due to improper CSS imports

### ISSUE THREAD

**Issue by blacksoulgem95** [couds/react-bulma-components#325]
**Describe the bug**
```
error - ./node_modules/react-bulma-components/lib/components/box/box.sass
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/react-bulma-components/lib/components/box/index.js
```

**To Reproduce**
1. Create a Nextjs package
2. install react bulma components
3. Add a component to any js that is not _app.js

**Expected behavior**
The CSS should be imported as CSS Modules and not as plain CSS in components

**Screenshots**

**Versions**
- `react-bulma-components:`: 3.4.0
- `bulma`: 0.9.1
- `react`: 17
- `next`: 10
- Browser: (e.g. Firefox version 67) All

**Additional context**

**Comment by couds** [comment]
Hi @blacksoulgem95 

if possible I would recommend to use v4 instead of v3. if that's not possible try to use the basic setup instead of the advanced https://github.com/couds/react-bulma-components/tree/v3.4.0#basic

V3 was not made to use css modules. IMO Bulma css it mean to be global (not to be use as CSS modules) it have a lot of cross modifiers

Please check basic configuration, you can instead of importing the whole bulma.css load each saas file. this way you have more control about hot the css its imported
