### ISSUE TITLE
Modal is not working 

### ISSUE THREAD

**Issue by moetezch** [couds/react-bulma-components#67]
Hello,
Modal doesn't seem to work 
``
        <OpenModal modal={{ closeOnEsc:  false }}>
          <Modal.Content>
            <Section style={{ backgroundColor: "white" }}>
              Click on the
              "X"
               button on the top-right button to close the Modal (pass closeOnEsc=false to the modal to avoid closing it with the keyboard)
            </Section>
          </Modal.Content>
        </OpenModal>
``
And I am getting this error : 

Unhandled Rejection (Invariant Violation): Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

 Please help me.

**Comment by couds** [comment]
Hi @moetezch I think the storybook documentation was misleading in how to use the Modal component.The OpenModal in the storybook its a helper component to be able to handle the open state in the storybook. (I'm changing that documentation for v2).

The actual code need to be something like this. (I didn't test it the code I wrote it directly so maybe have typos. but I think you can get the idea.

```
import React from 'react';
import { Modal } from 'react-bulma-components';

export default class ModalExample extends React.Component {
  state = { open: false };
  render() {
    return (
      <div>
         <button onClick={() => this.setState({ open: true })}>Open</button>
         <Modal show={this.state.open} onClose={() => this.setState({ open: false })}>MODAL CONTENT</Modal>
      </div>
    )
  }
}
```

The important part of the code its `<Modal show={this.state.open} onClose={() => this.setState({ open: false })}>MODAL CONTENT</Modal>` that is the actual modal, you need to handle the state of the modal your self as another controlled component (passing `true/false` to the show prop).

I hope this help, I'm working on improving the docs because seem to be a lot of misunderstanding on it.

Let me know if this help

**Comment by moetezch** [comment]
Yeah It's working. 

Thank you so much :)
