### ISSUE TITLE
Route Not working inside container 

### ISSUE THREAD

**Issue by IvanMiIosevic** [couds/react-bulma-components#71]
Hi,
(Sorry, i'm opening a lot of issues ^^')

I wanted to try the container component but my routes are not working when inside the container :(

this is my structure : 
```js
        <Router>
          <div>
            <MainNav />
            <Container breakpoint="widescreen">
              <Route exact path="/" component={Home} />
              <Route path="/about" component={About} />
              <Route path="/snippets" component={Snippets} />
            </Container>
          </div>
        </Router>
```

Seems weird because if i wrapped the routes inside a div it is working... Tried to render the container as a `div`but it is still not working.

My `Link` tag are changing this URL but the route is not rendering the correct component. Works again if i remove the `Container` component.

Do you have an idea on what's going on ?

**Comment by couds** [comment]
Hi @IvanMiIosevic  I just release the version 2, this should be fixed on this version.

The issue was caused because the Container component was declared as a react.PureComponent so when the route change the props of the container didn't change and the render method was not called. Now the components are functional ones so this should be working as expected.

Let me know if you have issues with the new version.

Thanks

**Comment by IvanMiIosevic** [comment]
Thank you again !

I updated with `npm install react-bulma-components@next --save` and it works 👌 

GG you are doing a great job 👍

**Comment by couds** [comment]
Hi. You can update to version 2 (it's already released)

=)
