### ISSUE TITLE
Navbar not working anymore even with props to toggle it 

### ISSUE THREAD

**Issue by IvanMiIosevic** [couds/react-bulma-components#72]
Hi,

Yeah... That's me again, sorry :disappointed: ...

Navbar doesn't work anymore in 2.0.0-8, i tried to add `active` or `is-active` or anything i could find in the source code (i don't understand all of it so i've probably missed something) but it's not working on storybook too anymore so i'm guessing something is wrong ?
Can you check please ?

I'll be glad to help if i can !

thanks for the hard work :+1:

**Comment by couds** [comment]
Hi Ivan. The navbar it's now a controlled component. It's mean that now you have to keep the state of the menu (open/close).

The navbar now receive a bool prop called active, when `true` the mobile menu will be open. In the storybook if you go to the knob tab In the bottom panel you can see a checkbox to open/close the menu (this menu it's only displayed on mobile viewports, you can change it using the tab viewports on the same bottom panel)

Let me know if it's help or if the issue is still happening.

Thanks

**Comment by IvanMiIosevic** [comment]
Sorry... was not aware of the "Knobs" tab ... I'm so dumb 

I was setting all the active props to `true` to test but i guess i was doing something wrong
Thank you ! you can close this

**Comment by couds** [comment]
@IvanMiIosevic  dont worry. I will try to improve the documentation when I can. right now I don't have enough time >.<
