### ISSUE TITLE
Documentation - To Use

### ISSUE THREAD

**Issue by andrewoh531** [couds/react-bulma-components#77]
Firstly thanks for this OSS, I can see this saving a lot of time for those who are looking to use react + bulma.

In the base README.md file there is an instruction to `Follow the instructions for creating a _variables.sass for your project` which got me a little confused as there aren't any links for doing this nor was it necessary. Is this only for overriding variables? The documentation on [npmjs](https://www.npmjs.com/package/react-bulma-components) does not have this line.

**Comment by couds** [comment]
Hi @andrewoh531 

The npm documentation its not updated yet, sorry for the confusion. 

The setup of the `_variables.sass` it indeed necessary if you import the components directly (Ex: `import Columns from 'react-bulma-components/lib/components/columns'` this is because they look for this file for the bulma variables, but is you use the bundled version the setup of this file should not be required)

I hope this clarify a little this.

Let me know.

Thanks

**Comment by andrewoh531** [comment]
Thanks for the clarification!

**Comment by verheyenkoen** [comment]
Is this possible with the node-sass-chokidar approach (without ejecting)? Can't get it to work with directly imported components...

**Comment by couds** [comment]
Hi @verheyenkoen I think that right now its not possible to import directly the components without ejecting =(. this is because the alias we use to import the variables.sass.
