### ISSUE TITLE
Colors not set in default Bulma SASS but implied in project components

### ISSUE THREAD

**Issue by brandonratz** [couds/react-bulma-components#83]
## Problem

The prop `color` has no effect when using the Tile component with Bulma using modular style component imports. 

This is because the Bulma package itself has no styles for colors in `bulma/sass/grid/_tiles.sass`. By comparison, using the Hero component, the `color` prop works, the styles are set correctly, ie `.hero.is-primary`.

```
<Tile renderAs="article" kind="child" notification color="primary">
  <Heading>Tile...</Heading>
</Tile>
```

_I suspect other components will suffer from this but haven't inspected further yet._

## Proposed Solution

Should styles be added to the component's themselves to support colors since it is implied to work via the Storybook?

--or--

Should the styles be added to Bulma directly?

**Comment by couds** [comment]
Hi @brandonratz That behavior its from bulma, I think I will change the component a little and remove the color and notification prop because its not from bulma, and change the storybook to use the renderAs of the Tile to render as a Notification.

I dont want to add more styles that are not in bulma. 

For now what you can do its the follow

```
<Tile renderAs={Notification} color="primary">
.... other components, html, etc
</Tile>
```
If you want to keep using the `renderAs="article"` probably you should warp it as another component. for Example:

notification-article.js
```
export default (props) => (
<Notification renderAs="article" {...props} />
);
```

another component:
```
import NotificationArticle from 'your-path-to-notification-article-component';
... other imports

export default () => {
<Tile renderAs={NotificationArticle} color="primary">
.... other components, html, etc
</Tile>
}
```

What do you think?
